config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing_service.urls", namespace="mailing_service")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import RegisterView, UserConfirmEmailView, EmailConfirmationSentView, EmailConfirmedView, \
    EmailConfirmationFailedView, UserForgotPasswordView, UserPasswordResetConfirmView, LoginUserView, LogoutUserView, \
    ProfileUserDetailView, ProfileUserUpdateView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutUserView.as_view(next_page='mailing_service:home'), name='logout'),

    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    # Подтверждение email
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('profile/<int:pk>/', ProfileUserDetailView.as_view(), name='profile_user'),
    path('<int:pk>/profile_edit/', ProfileUserUpdateView.as_view(), name='profile_edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('can_ban_user', "can ban user"),
            ('can_stop_mailing', 'can stop mailing')
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import CustomUser
from .services import FormClean


class ProfileForm(FormClean, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Придумайте имя пользователя',
            'help_text': "!@@@@@"
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Ваш email',
            'help_text': "!@@@@@"
        })
        self.fields['phone_number'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите ваш телефон'
        })
        self.fields['avatar'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['country'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Выберите страну'
        })

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'phone_number', 'avatar', 'country',)
        exclude = ('password1', 'password2')

    def clean_password(self):
        password = self.cleaned_data.get('password')
        password_user = CustomUser.objects.get(password=password)
        return password_user.password

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if CustomUser.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("Пользователь с таким username уже существует.")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if CustomUser.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("Пользователь с таким Email уже существует.")

        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен состоять только из цифр!")
        return phone_number

    def clean(self):
        """Валидация на проверку полей (чтобы не было запрещенных слов)"""
        super().clean()


class LoginUserForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите ваш email'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })


class CustomUserCreationForm(FormClean, UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите имя пользователя'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите свою почту'
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-select'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-select'
        })

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2',)

    def clean(self):
        """Валидация на проверку полей (чтобы не было запрещзенных слов)"""
        super().clean()

users/views.py
import os
import random

from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.models import Site
from django.views import View
from django.views.generic import CreateView, TemplateView, ListView, DetailView, UpdateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import send_mail
from django.shortcuts import redirect

from .forms import CustomUserCreationForm, LoginUserForm, ProfileForm
from .models import CustomUser
from .services import UserIsNotAuthenticated

User = get_user_model()


class ProfileUserDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'users/profile_user.html'
    context_object_name = 'profile_user'


class ProfileUserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    template_name = 'users/register.html'
    form_class = ProfileForm

    context_object_name = "profile_edit"

    def get_success_url(self):
        return reverse("users:profile_user", args=[self.kwargs.get("pk")])


class LoginUserView(LoginView):
    form_class = LoginUserForm


class LogoutUserView(LoginRequiredMixin, LogoutView):
    success_url = reverse_lazy('mailing_service:home')


class RegisterView(UserIsNotAuthenticated, CreateView):
    template_name = 'users/register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('mailing_service:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Функционал для отправки письма и генерации токена
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current().domain
        send_mail(
            'Подтвердите свой электронный адрес',
            f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://{current_site}{activation_url}',
            os.getenv('EMAIL_HOST_USER'),
            [user.email],
            fail_silently=False,
        )
        return redirect('users:email_confirmation_sent')


class UserConfirmEmailView(View):
    """Класс представления подтверждения почты"""
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmationSentView(TemplateView):
    """Представление письмо отправлено"""
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmedView(TemplateView):
    """Подтверждение активации"""
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    """Подтверждение, что не активирован аккаунт"""
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    # form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлена на ваш email'
    subject_template_name = 'users/password_subject_reset_mail.txt'
    email_template_name = 'users/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    # form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Пароль успешно изменен. Можете авторизоваться на сайте.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context

users/templates/users/email_confirmation_failed.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
</div>
{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию!</p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Вход{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-4"></div>
    <div class="col-4 text-center shadow p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
            <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-success">
                        Войти
                    </button>
                    <a class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'mailing_service:home' %}">Назад</a>
                    <a class="px-3 py-3 btn btn-lg btn-block btn-outline" href="{% url 'users:password_reset' %}">Забыли
                        пароль?</a>
                </div>
            </form>
        </div>
    </div>
    <div class="col-4"></div>
</div>
{% endblock %}

users/templates/users/password_reset_mail.html
{% autoescape off %}
    
    Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя на {{ site_name }}.

	Перейдите на следующую страницу и выберите новый пароль:
	{% block reset_link %}
	    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	Ваше имя пользователя, если вы забыли: {{ user.get_username }}

	Спасибо за использование нашего сайта!

	The {{ site_name }} team

{% endautoescape %}

users/templates/users/profile_user.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Профиль{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Профиль</h1>
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-3"></div>
    <div class="card-body col-6 text-center">
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <h3 class="form-label">Имя пользователя</h3>
            <h1 class="form-control">{{ profile_user.username }}</h1>

            <h3 class="form-label">Email адрес</h3>
            <h1 class="form-control">{{ profile_user.email }}</h1>

            <h3 class="form-label">Номер телефона</h3>
            <h1 class="form-control">{{ profile_user.phone_number }}</h1>

            <h3 class="form-label">Страна</h3>
            <h1 aria-label="Disabled input example" class="form-control">{{ profile_user.country }}</h1>

            <h3 class="form-label">Аватар</h3>
            <img src="{{ profile_user.avatar | media_filter }}" class="image" width="200" height="200">
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <a class="btn btn-lg btn-block btn-outline-success" href="{% url 'users:profile_edit' profile_user.pk%}">Редактировать</a>
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mailing_service:home' %}">Назад</a>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Регистрация{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        {% if user.is_active %}
            Обновление профиля
        {% else %}
            Регистрация
        {% endif %}
    </h1>
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-3"></div>
        <div class="card-body col-6 text-center shadow p-3 mb-5 bg-body-tertiary rounded">
            <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    {{ form.non_field_errors }}
                    {{ form.as_p }}
                    {% if user.is_active %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-success">
                            Сохранить
                        </button>
                    {% else %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-success">
                            Регистрация
                        </button>
                    {% endif %}
                        <a class="btn btn-lg btn-block btn-outline-primary"
                           href="{% url 'mailing_service:home' %}">Назад</a>
                </div>
            </form>
        </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title text-center">
            <h4>Запрос на восстановление пароля на сайте</h4>
        </div>
        <form class="text-center" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Вход на сайт</p>
</div>

{% endblock %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Установить новый пароль</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark mt-2">Подтвердить</button>
        </form>
    </div>
</div>
{% endblock %}