config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing_service.urls", namespace="mailing_service")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_service/urls.py
from django.urls import path

from .views import (MailingCreateView, MailingDeleteView,
                    MailingUpdateView, MailingView, MessageCreateView,
                    MessageDeleteView, MessageDetailView, MessageUpdateView,
                    UserMailCreateView, UserMailDeleteView, UserMailDetailView,
                    UserMailUpdateView, MailingAttemptView, UserRegisterView, UserBanView, MailingListView,
                    MailingSendView, MailingStopSendView)

app_name = "mailing_service"

urlpatterns = [
    path("", MailingView.as_view(), name="home"),
    path("<int:pk>/mailing_send/", MailingSendView.as_view(), name="mailing_send"),
    path("<int:pk>/mailing_stop/", MailingStopSendView.as_view(), name="mailing_stop"),

    path("mailing_add/", MailingCreateView.as_view(), name="mailing_add"),
    path("mailing_list/", MailingListView.as_view(), name="mailing_detail"),
    path("<int:pk>/update_mailing/", MailingUpdateView.as_view(), name="mailing_update"),
    path("<int:pk>/delete_mailing/", MailingDeleteView.as_view(), name="mailing_delete"),

    path("user_mail_create/", UserMailCreateView.as_view(), name="user_mail_create"),
    path("user_mail_list/", UserMailDetailView.as_view(), name="user_mail_detail"),
    path("<int:pk>/update_user/", UserMailUpdateView.as_view(), name="user_mail_update"),
    path("<int:pk>/delete_user/", UserMailDeleteView.as_view(), name="user_mail_delete"),

    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path("message_list/", MessageDetailView.as_view(), name="message_detail"),
    path("<int:pk>/update_message/", MessageUpdateView.as_view(), name="message_update"),
    path("<int:pk>/delete_message/", MessageDeleteView.as_view(), name="message_delete"),

    path("mailing_attempt/", MailingAttemptView.as_view(), name="mailing_attempt"),
    path("users_list/", UserRegisterView.as_view(), name="users_register"),
    path("<int:pk>/users_ban/", UserBanView.as_view(), name="users_ban"),
]

users/urls.py
from django.urls import path

from .views import RegisterView, UserConfirmEmailView, EmailConfirmationSentView, EmailConfirmedView, \
    EmailConfirmationFailedView, UserForgotPasswordView, UserPasswordResetConfirmView, LoginUserView, LogoutUserView, \
    ProfileUserDetailView, ProfileUserUpdateView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutUserView.as_view(next_page='mailing_service:home'), name='logout'),

    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    # Подтверждение email
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('profile/<int:pk>/', ProfileUserDetailView.as_view(), name='profile_user'),
    path('<int:pk>/profile_edit/', ProfileUserUpdateView.as_view(), name='profile_edit'),
]

mailing_service/views.py
import os
import smtplib

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from dotenv import load_dotenv

from mailing_service.forms import MailingForm, MessageForm, UserMailForm
from mailing_service.models import Mailing, MailingAttempt, Message, UserMail
from mailing_service.services import send_mailing, GetListMailing

from users.models import CustomUser

load_dotenv(override=True)


class MailingView(ListView):
    """Класс представления Всех рассылок на главной странице"""

    model = Mailing
    template_name = "mailing_service/home.html"
    context_object_name = "mailing"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context["user_mail"] = UserMail.objects.all()
        context["mailing_all_started"] = Mailing.objects.filter(status="Запущена")

        if self.request.user.is_authenticated:
            context['user_usermail'] = UserMail.objects.filter(owner=self.request.user)
            context['user_mailing_started'] = Mailing.objects.filter(owner=self.request.user, status='Запущена')
            context['user_mailing'] = Mailing.objects.filter(owner=self.request.user)

        return context

    def get_queryset(self):
        """Настройка серверного кэширования главной страницы"""
        return GetListMailing.get_list_mailing_from_cache()


class MailingStopSendView(LoginRequiredMixin, DetailView):
    """Класс отключения рассылок администратором"""
    model = Mailing
    template_name = "mailing_service/mailing_stop.html"
    context_object_name = "mailing_stop"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.has_perm("can_stop_mailing"):
            self.object.status = "Отключена"
            self.object.save()
        return self.object


class MailingSendView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = "mailing_service/mailing_send.html"
    context_object_name = "mailing_send"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        if self.object.owner == self.request.user and self.object.status == "Создана":
            try:
                send_mailing(self)  # Функция в разделе сервисы, отправляет сообщения по рассылке
            except smtplib.SMTPException as error:
                MailingAttempt.objects.create(mailing=self.object, mail_response=error, status='Не успешно')
        return self.object


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Класс представления создания рассылки"""

    model = Mailing
    template_name = "mailing_service/mailing_add.html"
    context_object_name = "mailing_add"

    form_class = MailingForm
    success_url = reverse_lazy("mailing_service:mailing_detail")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user

        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        # Передаем текущего пользователя в форму
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


# @method_decorator(cache_page(60), name='dispatch')
class MailingListView(LoginRequiredMixin, ListView):
    """Класс представления детальной рассылки"""

    model = Mailing
    template_name = "mailing_service/mailing_detail.html"
    context_object_name = "mailing_detail"

    def get_queryset(self):
        user = self.request.user

        if user.has_perm('mailing_service.can_view_mailing'):
            return Mailing.objects.all()
        return Mailing.objects.filter(owner=user)

    # def get_form_class(self):
    #     user = self.request.user
    #     if user == self.object.owner or user.has_perm('catalog.delete_product'):
    #         return super().get_form_class()
    #     raise PermissionDenied

    # def get_object(self, queryset=None):
    #     self.object = super().get_object(queryset)
    #     if self.object.owner == self.request.user:
    #         return self.object
    #     raise PermissionDenied


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Класс представления обновления рассылки"""

    model = Mailing
    template_name = "mailing_service/mailing_add.html"
    context_object_name = "mailing_update"

    form_class = MailingForm

    def get_success_url(self):
        return reverse("mailing_service:mailing_detail")

    def get_form_class(self):
        """
        Проверка чтобы пользователь был владельцем продукта и тогда может его изменять
        и если у пользовтаеля есть право can_unpublish_product
        """
        user = self.request.user
        if user == self.object.owner:
            return MailingForm
        raise PermissionDenied

    def get_form_kwargs(self):
        # Передаем текущего пользователя в форму
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """Класс представления удаления рассылки"""

    model = Mailing
    template_name = "mailing_service/mailing_delete.html"
    context_object_name = "mailing_delete"

    success_url = reverse_lazy("mailing_service:mailing_detail")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return super().get_form_class()
        raise PermissionDenied


@method_decorator(cache_page(60), name='dispatch')
class UserMailDetailView(LoginRequiredMixin, ListView):
    """Класс представления детально получателя рассылки"""

    model = UserMail
    template_name = "mailing_service/user_mail_detail.html"
    context_object_name = "user_mail_detail"

    def get_queryset(self):
        user = self.request.user

        if user.has_perm('mailing_service.can_view_user_mail'):
            return UserMail.objects.all()
        return UserMail.objects.filter(owner=user)

    # def get_object(self, queryset=None):
    #     self.object = super().get_object(queryset)
    #     if self.object.owner == self.request.user:
    #         return self.object
    #     raise PermissionDenied


class UserMailCreateView(LoginRequiredMixin, CreateView):
    """Класс представления создания получателей рассылки"""

    model = UserMail
    template_name = "mailing_service/user_mail_create.html"
    context_object_name = "user_mail_create"

    form_class = UserMailForm
    success_url = reverse_lazy("mailing_service:user_mail_detail")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()

        return super().form_valid(form)


class UserMailUpdateView(LoginRequiredMixin, UpdateView):
    """Класс представления обновления получателей рассылки"""

    model = UserMail
    template_name = "mailing_service/user_mail_create.html"
    context_object_name = "user_mail_update"

    form_class = UserMailForm

    def get_success_url(self):
        return reverse("mailing_service:user_mail_detail")

    def get_form_class(self):
        """
        Проверка чтобы пользователь был владельцем продукта и тогда может его изменять
        и если у пользовтаеля есть право can_unpublish_product
        """
        user = self.request.user
        if user == self.object.owner:
            return UserMailForm
        raise PermissionDenied


class UserMailDeleteView(LoginRequiredMixin, DeleteView):
    """Класс представления удаления получателей рассылки"""

    model = UserMail
    template_name = "mailing_service/user_mail_confirm_delete.html"
    context_object_name = "user_mail_delete"

    success_url = reverse_lazy("mailing_service:user_mail_detail")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return super().get_form_class()
        raise PermissionDenied


@method_decorator(cache_page(60), name='dispatch')
class MessageDetailView(LoginRequiredMixin, ListView):
    """Класс представления писем"""

    model = Message
    template_name = "mailing_service/message_detail.html"
    context_object_name = "message_detail"

    def get_queryset(self):
        user = self.request.user

        if user.has_perm('mailing_service.can_view_message'):
            return Message.objects.all()
        return Message.objects.filter(owner=user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Класс представления создания писем"""

    model = Message
    template_name = "mailing_service/message_create.html"
    context_object_name = "message_create"

    form_class = MessageForm
    success_url = reverse_lazy("mailing_service:message_detail")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()

        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Класс представления обновления писем"""

    model = Message
    template_name = "mailing_service/message_create.html"
    context_object_name = "message_update"

    form_class = MessageForm

    def get_success_url(self):
        return reverse("mailing_service:message_detail")

    def get_form_class(self):
        """
        Проверка чтобы пользователь был владельцем продукта и тогда может его изменять
        и если у пользовтаеля есть право can_unpublish_product
        """
        user = self.request.user

mailing_service/templates/mailing_service/basic_design.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Главная страница{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
    <body>
        {% block header %}
        {% endblock %}
        <div class="container ">
            {% block content %}
            {% endblock %}

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        SendMail
                        <small class="d-block mb-3 text-muted">&copy; 2025</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Категории</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'mailing_service:mailing_detail' %}">Рассылки</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Дополнительно</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Мы пишем</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>О нас</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Контакты</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>

        <script src="/static/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

mailing_service/templates/mailing_service/home.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Главная страница{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">SendMail - это отличный вариант создания кампаний для презентаций ваших продуктов и рекламных
        рассылок</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing_service:mailing_detail' %}">Запустить рассылку</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img src="media/mailing_service/photo/all_send_mail.jpg" width="270" height="200">
                <h4 class="my-0 font-weight-normal">Рассылки пользователям</h4>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <p class="card-title pricing-card-title">У вас: {{user_mailing.count}} шт.</p>
                {% else %}
                    <p class="card-title pricing-card-title">Всего: {{mailing.count}} шт.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <img src="media/mailing_service/photo/active_mailing.jpg" width="250" height="200">
                <h4 class="my-0 font-weight-normal">Активные рассылки</h4>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <p class="card-title pricing-card-title">У вас: {{user_mailing_started.count}} шт.</p>
                {% else %}
                    <p class="card-title pricing-card-title">Всего: {{mailing_all_started.count}} шт.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card mb-6 box-shadow">
            <div class="card-header">
                <img src="media/mailing_service/photo/user_mail.jpg" width="200" height="200">
                <h4 class="my-0 font-weight-normal">Уникальные получатели</h4>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <p class="card-title pricing-card-title">У вас: {{user_usermail.count}} пользователей.</p>
                {% else %}
                    <p class="card-title pricing-card-title">Всего: {{user_mail.count}} пользователей.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mailing_add.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Главная страница{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Добавляем рассылку</h1>
</div>

{% endblock %}

{% block content %}
<div class="card-body">
    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                {% if object %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
            </button>
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing_service:mailing_detail' %}">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mailing_attempt_detail.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Статистика</h1>
    <p class="lead">Вы можете контролировать и анализировать отправку сообщений</p>
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Время попытки</th>
            <th scope="col">Статус</th>
            <th scope="col">Ответ почтового сервера</th>
            <th scope="col">Рассылка</th>
        </tr>
        </thead>
        <tbody>
        {% for attempt in mailing_attempt %}
        <tr>
            <td>{{ attempt.datetime_attempt|date:"d.m.Y H:i:s" }}</td>
            <td>{{ attempt.status }}</td>
            <td>{{ attempt.mail_response }}</td>
            <td>{{ attempt.mailing }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mailing_stop.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}{{ title }}{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
{% endblock %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Рассылка №{{mailing_stop.id}} отключена.</h4>
</div>
{% endblock %}

mailing_service/templates/mailing_service/message_detail.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Сообщения для отправки пользователям</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing_service:message_create' %}">Создать
        сообщение</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Заголовок</th>
            <th scope="col">Текст письма</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for message in message_detail %}
        <tr>
            <td>{{ message.head_letter }}</td>
            <td>{{ message.body_letter }}</td>
            <td>
                {% if user.is_authenticated %}
                <a href="{% url 'mailing_service:message_update' message.pk%}" class="text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                    </svg>
                </a>
                <a class="btn btn-close" aria-label="Close"
                   href="{% url 'mailing_service:message_delete' message.pk%}"></a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing_service/templates/mailing_service/user_mail_detail.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Получатель{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SendMail Service</h1>
    <p class="lead">Пользователи для отправки сообщений</p>
    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing_service:user_mail_create' %}">Добавить
        получателя</a>
    {% endif %}
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Email</th>
            <th scope="col">Ф.И.О.</th>
            <th scope="col">Комментарий</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for user_mail in user_mail_detail %}
        <tr>
            <td>{{ user_mail.email }}</td>
            <td>{{ user_mail.fullname }}</td>
            <td>{{ user_mail.comment }}</td>
            <td>
                {% if user.is_authenticated %}
                <a href="{% url 'mailing_service:user_mail_update' user_mail.pk%}" class="text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                    </svg>
                </a>
                <a class="btn btn-close" aria-label="Close"
                   href="{% url 'mailing_service:user_mail_delete' user_mail.pk%}"></a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing_service/templates/mailing_service/user_register_ban.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}Блокировка{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блокировка пользователя</h1>
</div>

{% endblock %}

{% block content %}
<form method="post" action="" class="form-floating">
    {% csrf_token %}
    <div class="row text-center">
        <div class="card mb-4 box-shadow">
            {% if user_ban.is_active %}
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">Вы дейстительно хотите заблокировать "{{user_ban.email}}" ?</h1>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3 text-center">
                        <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Заблокировать</button>
            {% else %}
                    <div class="card-header">
                <h1 class="my-0 font-weight-normal">Вы дейстительно хотите разблокировать "{{user_ban.email}}" ?</h1>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3 text-center">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-success">Разблокировать</button>
            {% endif %}
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing_service:users_register' %}">Отменить</a>
                </ul>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing_service/templates/mailing_service/user_register_view.html
{% extends 'mailing_service/basic_design.html' %}
{% load my_tags %}
{% block title %}users{% endblock %}

{% block header %}
{% include 'mailing_service/includes/header_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Пользователи сайта</h1>
    <p class="lead"></p>
</div>

{% endblock %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Email</th>
            <th scope="col">Username</th>
            <th scope="col">Последний вход</th>
            <th scope="col">Страна</th>
            <th scope="col">Статус активации True|False</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.last_login }}</td>
            <td>{{ user.country }}</td>
            <td>{{ user.is_active }}</td>
            <td>
                {% if user.is_active %}
                    <a class="btn btn-lg btn-block btn-outline-danger" href="{% url 'mailing_service:users_ban' user.pk%}">Заблокировать</a>
                {% else %}
                    <a class="btn btn-lg btn-block btn-outline-success" href="{% url 'mailing_service:users_ban' user.pk%}">Разблокировать</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}